language: "python"
dist: "bionic"
python:
  - "3.8.5"
  - "2.7"
  - "3.6"
  - "nightly"
services:
  - "docker"


install:
  - "pip install -r requirements.txt"

befoe_script:
 # - "pylint src/*py"
 # - "pylint test/system/*py"
  - "python -m unittest test/sytem/test_system.py"
  - "docker-compose up -d"
  - "docker container ls"

script:
  - "python -m unittest test/system/test_system.py"

after_script:
  - "docker-compose down"
  
