language: "python"
dist: "focal"
python:
  - "3.8.5"
  - "2.7"
  - "3.6"
  - "nightly"
services:
  - "docker"





install:
  - "pip3 install -r requirements.txt"

before_script:
 # - "pylint src/*py"
 # - "pylint test/system/*py"
  - "python3 -m unittest test/sytem/test_home.py"
  - "docker image build -t tshoot_webapp ." 
  - "docker-compose up -d"
  - "docker container ls"

script:
  - "python3 -m unittest test/system/test_home.py"

after_script:
  - "docker-compose down"
  
