language: "python"
dist: "focal"
python:
  - "3.8.5"
  - "3.6"
  - "nightly"
services:
  - "docker"





install:
  - "pip install -r requirements.txt"

before_script:
 # - "pylint src/*py"
 # - "pylint test/system/*py"
  - "ls"
  - "cd src"
  - "python -m unittest test_home.py"
  #- "python -m unittest test/system/test_home.py"
  - "cd .."
  - "ls"
  - "docker image build -t tshoot_webapp ." 
  - "docker-compose up -d"
  - "docker container ls"

script:
  - "ls"
  - "cd src"
  - "ls"
  - "python -m unittest test_home.py"

after_script:
  - "docker-compose down"
  
