---
# Version 3.7 for compose files corresponds with
# Docker engine 18.06.0 and newer (per Docker docs).
version: "3.7"

# Nested dictionary of containers to create. I'm demonstrating
# 3 tshoot_webapp apps each exposing a different public TCP port. This is
# a "scale out" technique and you could put a load balancer in front.
services:
  tshoot_webapp1:
    build: "."
    ports:
      - "5000:5000/tcp"
  web:
    build: "nginx"
    ports:
      - "443:443/tcp"

...
